name: Checks

on:
  push:
  pull_request:

jobs:
  backend:
    name: Backend Tests & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start services
        run: docker compose build

      - name: Wait for database
        run: docker compose exec backend python manage.py wait_for_db

      - name: Run tests
        run: docker compose exec backend python manage.py test

      - name: Run lint
        run: docker compose exec backend flake8 .

      - name: Shutdown
        if: always()
        run: docker compose down

  frontend:
    name: Frontend Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run lint
        run: |
          cd frontend
          npm run lint
